/**
 * Zep Ontology - Custom Entity and Edge Types
 *
 * Defines the knowledge graph structure for content management.
 * These types will be registered with Zep Cloud to enable
 * context extraction and retrieval.
 *
 * @see https://help.getzep.com/ontology
 */

/**
 * Entity Type Definitions
 *
 * Each entity type represents a node in the knowledge graph.
 * Zep will automatically extract and classify information into these types.
 */

export const ENTITY_TYPES = {
  /**
   * EstrategiaConteudo - Content Strategy
   *
   * Represents a content strategy defined by the user or strategist agent.
   * Contains the core themes, voice, and target audience for content creation.
   */
  EstrategiaConteudo: {
    name: "EstrategiaConteudo",
    description: "Estratégia de conteúdo definida com tema, tom de voz e público-alvo",
    fields: {
      temaPrincipal: {
        type: "string",
        description: "Tema central da estratégia",
        required: true,
      },
      tomDeVoz: {
        type: "string",
        description: "Tom de voz predominante (ex: formal, descontraído, humorístico)",
        required: false,
      },
      publicoAlvo: {
        type: "string",
        description: "Público-alvo da estratégia",
        required: false,
      },
      plataformas: {
        type: "string",
        description: "Plataformas de atuação (ex: instagram, twitter, linkedin)",
        required: false,
      },
      validadeInicio: {
        type: "string",
        description: "Data de início (ISO 8601)",
        required: false,
      },
      validadeFim: {
        type: "string",
        description: "Data de fim (ou 'present' para vigente)",
        required: false,
      },
    },
  },

  /**
   * PostGerado - Generated Post
   *
   * Represents a piece of content generated by the system.
   * Tracks all posts across their lifecycle from draft to published.
   */
  PostGerado: {
    name: "PostGerado",
    description: "Conteúdo de post gerado pelo sistema",
    fields: {
      tipo: {
        type: "string",
        description: "Tipo (text, image, carousel, video, story)",
        required: true,
      },
      plataforma: {
        type: "string",
        description: "Plataforma (instagram, twitter, linkedin, tiktok)",
        required: true,
      },
      topico: {
        type: "string",
        description: "Tópico abordado no post",
        required: false,
      },
      status: {
        type: "string",
        description: "Status (draft, scheduled, published, archived)",
        required: true,
      },
      libraryItemId: {
        type: "string",
        description: "ID na biblioteca interna",
        required: false,
      },
    },
  },

  /**
   * IdeiaConteudo - Content Idea
   *
   * Represents an idea for future content.
   * Can be suggested by users or agents.
   */
  IdeiaConteudo: {
    name: "IdeiaConteudo",
    description: "Ideia para conteúdo futuro",
    fields: {
      descricao: {
        type: "string",
        description: "Descrição da ideia",
        required: true,
      },
      categoria: {
        type: "string",
        description: "Categoria (tutorial, inspiração, promocional)",
        required: false,
      },
      prioridade: {
        type: "string",
        description: "Prioridade (alta, media, baixa)",
        required: false,
      },
    },
  },

  /**
   * AgendaPost - Scheduled Post
   *
   * Represents a scheduled entry in the content calendar.
   * Used by the calendario agent for scheduling.
   */
  AgendaPost: {
    name: "AgendaPost",
    description: "Post agendado no calendário editorial",
    fields: {
      dataAgendada: {
        type: "string",
        description: "Data de agendamento (ISO 8601)",
        required: true,
      },
      horaSugerida: {
        type: "string",
        description: "Horário sugerido (HH:MM)",
        required: false,
      },
      tipo: {
        type: "string",
        description: "Tipo de conteúdo",
        required: false,
      },
    },
  },

  /**
   * MarcaBrand - Brand Information
   *
   * Represents the user's brand and business information.
   * Core entity for personalization.
   */
  MarcaBrand: {
    name: "MarcaBrand",
    description: "Informações da marca e negócio",
    fields: {
      nome: {
        type: "string",
        description: "Nome da marca",
        required: true,
      },
      segmento: {
        type: "string",
        description: "Segmento de atuação",
        required: false,
      },
      valores: {
        type: "string",
        description: "Valores da marca (separados por vírgula)",
        required: false,
      },
    },
  },
} as const

/**
 * Edge Type Definitions
 *
 * Each edge type represents a relationship between entities.
 * Zep will automatically extract and classify relationships.
 */

export const EDGE_TYPES = {
  /**
   * DefiniuEstrategia - Defined Strategy
   *
   * User or agent defined a content strategy.
   * Connects: User/Marca -> EstrategiaConteudo
   */
  DEFINIU_ESTRATEGIA: {
    name: "DEFINIU_ESTRATEGIA",
    description: "Usuário ou agente definiu uma estratégia de conteúdo",
    fields: {
      dataDefinicao: {
        type: "string",
        description: "Data da definição (ISO 8601)",
        required: false,
      },
      contexto: {
        type: "string",
        description: "Contexto adicional da definição",
        required: false,
      },
    },
  },

  /**
   * GerouComBaseEm - Generated Based On
   *
   * A post was generated based on a strategy or idea.
   * Connects: Post -> EstrategiaConteudo | Post -> IdeiaConteudo
   */
  GERO_COM_BASE_EM: {
    name: "GEROU_COM_BASE_EM",
    description: "Post foi gerado com base em estratégia ou ideia",
    fields: {
      dataGeracao: {
        type: "string",
        description: "Data da geração (ISO 8601)",
        required: false,
      },
      agente: {
        type: "string",
        description: "Agente criador (criador, estrategista)",
        required: false,
      },
    },
  },

  /**
   * AgendadoPara - Scheduled For
   *
   * A post was scheduled for a specific date/time.
   * Connects: Post -> AgendaPost
   */
  AGENDADO_PARA: {
    name: "AGENDADO_PARA",
    description: "Post foi agendado para uma data específica",
    fields: {
      dataAgendamento: {
        type: "string",
        description: "Data do agendamento (ISO 8601)",
        required: false,
      },
      plataforma: {
        type: "string",
        description: "Plataforma do agendamento",
        required: false,
      },
    },
  },

  /**
   * PertenceACampanha - Belongs To Campaign
   *
   * Content belongs to a campaign or thematic initiative.
   * Connects: Post | EstrategiaConteudo -> Campanha
   */
  PERTENCE_A_CAMPANHA: {
    name: "PERTENCE_A_CAMPANHA",
    description: "Conteúdo pertence a uma campanha ou iniciativa",
    fields: {
      papel: {
        type: "string",
        description: "Papel na campanha (awareness, conversão, retenção)",
        required: false,
      },
    },
  },
} as const

/**
 * Type exports for TypeScript
 */
export type EntityType = keyof typeof ENTITY_TYPES
export type EdgeType = keyof typeof EDGE_TYPES

/**
 * Get all entity type names
 */
export function getEntityTypeNames(): string[] {
  return Object.keys(ENTITY_TYPES)
}

/**
 * Get all edge type names
 */
export function getEdgeTypeNames(): string[] {
  return Object.keys(EDGE_TYPES)
}
